---
title: "datascienceassignmnet2"
author: "Reilly Cameron"
date: "28/09/2020"
output: html_document
---

## Introduction

For freshwater mussel larvae (glochidia) to develop, they must for a brief period become parasitic on the gills of a host fish. Due to lack of knowledge on host fish for many freshwater mussels, the method of determining a host usually involves laboratory trials. These trials introduces a variety of potential hosts to juvenile mussels. Positive identification of of glochidia on wild host fish identification very difficult, which is why host trials are important to understand mussels and their hosts. Within this study Skipjack herring (Alosa chrysochloris) is noted as a host for two freshwater mussels including Elliptil crassidens and Reginaia ebenus. Their relationship to one another is based off of observations therefore laboratory trials will be completed to confirm the herring as a host as well as other related fish species. Skipjack Herring spawning migrations have been blocked or restricted by dams, but they remain common in rivers that continue to support large Skipjack Herring populations.

## Methods

32 gravid female R. ebenus were collected from the Alabama river and 10 gravid E. crassidens females from the Chewacla Creek. The mussels were kept in a recirculating aquarium at 18 degrees celsius. Using a needle and syringe the gills of each species were flushed with an saturated NaCl solution. This method scores glochidia as nonviable if they are either closed before exposure, or fail to close after exposed to the solution. Small-bodied fish such as Bluegill (Lepomis macrochirus), Largemouth bass (Micropterus salmoides) and Channel catfish (Ictalurs) were collected from ponds or commercial hatcheries using seining or backpack electrofishing. Larger river fish such as Gizzard shad (Dorsoma cepedianum) were collected using electrofishing. Skipjack was collected using hook and line and electrofishing caused them to sink quickly after being shocked. All fish were held in tanks at 18-21 degrees celsius and were fed three times a week. fishes were placed in tanks (one individual per tank) and were acclimatized to de-chlorinated tap water for a week before conducting host trials. For R. ebenus all fishes were placed in an inoculated suspension for 15 minutes. Four-six days after inoculation the gills were examined, no glochidia were examined except on 2 Gizzard shad but both fish died after due to handling stress. The same process was done for E. crassidens. No glochidia were found on the Bluegill.

## Results 

Of the 32 gravid R. ebenus collected on June 15, 11 broods were dominated by mature glochidia, 8 by early stage glochidia, and the remaining 12 by cleaved embryos that had not yet developed into glochidia. Batch 1 exhibited 86% viability and was used to inoculate Skipjack Herring. The remaining two composite batches had glochidial viabilities of 53% and 41%, respectively, and were discarded. All five E. crassidens females collected on March 26 were brooding early stage embryos and were therefore not examined for viability or used for experiments. The five females collected on April 3, one contained early stage embryos and mature glochidia, and the remaining four contained mature glochidia only. Viability of all E. crassidens broods was > 90%. Both composite batches of E. crassidens broods were used to inoculate fish. 97 Skipjack and 30 shad were captured totaling 127 fish. 3 of 11 Skipjack Herring died of unknown causes and a fourth died after handling. In the E. crassidens trials, 7 of 15 Skipjack Herring died, but only 1 of 15 Alabama Shad died of unknown causes. The remaining fish were sacrificed for gill excision. For R. ebenus, no individuals of any fish species had encapsulated glochidia on the gills 4–6 d after inoculation except for Gizzard Shad and Skipjack Herring. The single Skipjack Herring examined on day 11 had numerous encapsulated glochidia. this fish produced a total of 1160 juvenile mussels over 8 d, with the highest number of juveniles observed 2 d after excision (see figure 2). Gills of Alabama Shad excised 5–8 d after inoculation produced no live juvenile mussels even though encapsulated glochidia were ob- served. Gills excised on days 10–14 also contained encapsulated glochidia but produced very few live juveniles and metamorphosis success was < 1%. Peak production occurred on days 17–23; total juvenile production from these individuals ranged from 293 to 328/fish and metamorphosis success ranged from 50 to 60%. Herring excised 5–13 days after inoculation produced no juvenile mussels even though they contained encapsulated glochidia. Gills excised on day 16 produced 85 live juveniles with metamorphosis success of 28%. No live Skipjack Herring remained after day 16.

## Conclusions 

These trials are difficult with large river fish, as seen Skipjack and shad were very sensitive to handling and examination. Excision of the gills is important advancement which helps overcome some of the challenges associated with conduction host trials with these types of large river fish. A critical aspect of the gill excision technique is that it is successful within a specific time period.For E. crassidens on Alabama Shad, this window of opportunity lasted about two weeks, from 10 to 25 d after inoculation, but the period of highest metamorphosis success was even shorter, lasting from day 17–23. The window of opportunity for E. crassidens on Skipjack Herring and for R. ebenus appears to be similar. The results provide the first direct confirmation of Skipjack Herring as host for glochidia of R. ebenus and E. crassidens, and we provide the first report of the suitability of Alabama Shad as host for E. crassidens. these observations, support the idea that these two mussel species are strict specialists on Alosa spp. Within this study, all glochidia of R. ebenus were rejected quickly by 11 other fish species in six families. This study shows that these fishes (Skipjack and SHhad) are important for maintenance of populations of both mussel species. The confirmation of Alosa spp. as hosts for R. ebenus and E. crassidens supports the idea that dams and other river modifications that interrupt herring migrations are a key factor in the decline of these mussel species.

Hart, M.A., Hagg, W. R., Bringolf, R et al., (2018). Novel technique to identify large river host fish for freshwater mussel propagation and conservation. 9, 10-17. https://doi.org/10.1016/j.aqrep.2017.11.002 
